config/routes.rb
Rails.application.routes.draw do
  root :to => "web/boards#show"

  scope module: :web do
    resource :board, only: :show
    resource :session, only: [:new, :create, :destroy]
    resources :developers, only: [:new, :create]
  end

  namespace :admin do
    resources :users
  end

  namespace :api do
    namespace :v1 do
      resources :tasks, only: [:index, :show, :create, :update, :destroy]
    end
  end
end

app/models/admin.rb
class Admin < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/developer.rb
class Developer < User
end

app/models/manager.rb
class Manager < User
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :assignee, class_name: 'User', optional: true

  validates :name, presence: true
  validates :description, presence: true
  validates :author, presence: true
  validates :description, length: { maximum: 500 }

  state_machine initial: :new_task do
    event :develop do
      transition [:new_task, :in_qa, :in_code_review] => :in_development
    end

    event :qa do
      transition in_development: :in_qa
    end

    event :code_review do
      transition in_qa: :in_code_review
    end

    event :ready do
      transition in_code_review: :ready_for_release
    end

    event :release do
      transition ready_for_release: :released
    end

    event :archive do
      transition [:new_task, :released] => :archived
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :my_tasks, class_name: 'Task', foreign_key: :author_id
  has_many :assigned_tasks, class_name: 'Task', foreign_key: :assignee_id

  validates :first_name, presence: true, length: { minimum: 2 }
  validates :last_name, presence: true, length: { minimum: 2 }
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  include AuthHelper
  before_action :authenticate_user!, :authorize
  helper_method :current_user

  def authorize
    render(file: File.join(Rails.root, 'public/403.html'), status: 403, layout: false) if forbidden?
  end

  def forbidden?
    !current_user.is_a?(Admin)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def index
    @q = User.ransack(params[:q])
    @users = @q.result.order(:type).order(:id).page(params[:page]).per(10)
  end

  def edit
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to(admin_users_url)
    else
      render(:new_admin_user_url)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to(admin_users_url)
    else
      render(:edit)
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to(admin_users_path)
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :type)
  end
end

app/controllers/api/application_controller.rb
class Api::ApplicationController < ApplicationController
  include AuthHelper
  respond_to :json
end

app/controllers/api/v1/application_controller.rb
class Api::V1::ApplicationController < Api::ApplicationController
  RANSACK_DEFAULT_SORT = 'id ASC'.freeze

  def build_meta(collection)
    {
      count: collection.count,
      total_count: collection.total_count,
      current_page: collection.current_page,
      total_pages: collection.total_pages,
      per_page: collection.limit_value,
    }
  end

  def ransack_params
    params.to_unsafe_h.fetch(:q, { s: RANSACK_DEFAULT_SORT })
  end

  def page
    params.fetch(:page, 1)
  end

  def per_page
    per = params.fetch(:per, 10).to_i
    per > 100 ? 100 : per
  end

  def self.responder
    JsonResponder
  end
end

app/controllers/api/v1/tasks_controller.rb
class Api::V1::TasksController < Api::V1::ApplicationController
  def index
    tasks = Task.all.
      ransack(ransack_params).
      result.
      page(page).
      per(per_page)

    respond_with(tasks, each_serializer: TaskSerializer, root: 'items', meta: build_meta(tasks))
  end

  def show
    task = Task.find(params[:id])

    respond_with(task, serializer: TaskSerializer)
  end

  def create
    task = current_user.my_tasks.new(task_params)
    task.save

    respond_with(task, serializer: TaskSerializer, location: nil)
  end

  def update
    task = Task.find(params[:id])
    task.update(task_params)

    respond_with(task, serializer: TaskSerializer)
  end

  def destroy
    task = Task.find(params[:id])
    task.destroy

    respond_with(task)
  end

  private

  def task_params
    params.require(:task).permit(:name, :description, :author_id, :expired_at, :assignee_id, :state_event)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/auth_helper.rb
module AuthHelper
  def sign_in(user)
    session[:user_id] = user.id
  end

  def sign_out
    session[:user_id] = nil
  end

  def signed_in?
    current_user.present?
  end

  def authenticate_user!
    redirect_to(new_session_path) unless signed_in?
  end

  def current_user
    return if session[:user_id].blank?

    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/controllers/web/application_controller.rb
class Web::ApplicationController < ApplicationController
  include AuthHelper
  helper_method :current_user
end

app/controllers/web/boards_controller.rb
class Web::BoardsController < Web::ApplicationController
  before_action :authenticate_user!

  def show
    render react_component: 'TaskBoard', props: {}
  end
end

app/controllers/web/developers_controller.rb
class Web::DevelopersController < Web::ApplicationController
  def new
    @developer = Developer.new
  end

  def create
    @developer = Developer.new(developer_params)

    if @developer.save
      sign_in(@developer)
      redirect_to(:board)
    else
      render(:new)
    end
  end

  private

  def developer_params
    params.require(:developer).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/controllers/web/sessions_controller.rb
class Web::SessionsController < Web::ApplicationController
  def new
    @session = SessionForm.new
  end

  def create
    @session = SessionForm.new(session_params)

    if @session.valid?
      sign_in(@session.user)
      redirect_to(:board)
    else
      render(:new)
    end
  end

  def destroy
    sign_out
    redirect_to(:new_session)
  end

  private

  def session_params
    params.require(:session_form).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/users/_form.html.slim
= simple_form_for @user, as: :user, url: url do |f|
  p
    = f.input :first_name
    = f.input :last_name
    = f.input :email
    = f.input :password
    = f.input :type, as: :select, collection: ['Admin', 'Manager', 'Developer']
  p
    => f.button :submit, "Confirm", class: 'mdl-button--colored'
    = link_to "Back", admin_users_path, class: "mdl-button mdl-js-button mdl-button--raised"

app/views/admin/users/edit.html.slim
h4 Edit user
= render partial: 'form', locals: { user: @user, url: admin_user_path(@user) }

app/views/admin/users/index.html.slim
h3 Users list
.mdl-grid
  .mdl-cell.mdl-cell--2-col
    = link_to "Add new user", new_admin_user_path, class: "mdl-button mdl-js-button mdl-button--raised mdl-button--colored"
  .mdl-cell.mdl-cell--8-col
  .mdl-cell.mdl-cell--2-col
    = search_form_for(@q, url:admin_users_url, method: :get) do |f|
      .mdl-textfield.mdl-js-textfield
        = f.search_field :email_cont, class: 'mdl-textfield__input'
        = f.label :email_cont, class: 'mdl-textfield__label' do
          i.material-icons search
.mdl-grid
  table.mdl-cell--12-col.mdl-data-table.mdl-js-data-table.mdl-shadow--2dp
    thead
      tr
        th= sort_link(@q, :id, "#")
        th= sort_link(@q, :first_name, "First Name")
        th= sort_link(@q, :last_name, "Last Name")
        th= sort_link(@q, :email, "Email")
        th= sort_link(@q, :type, "Type")
        th scope="col"  Actions
    tbody
      - @users.each do |user|
        tr
          td= user.id
          td= user.first_name
          td= user.last_name
          td= user.email
          td= user.type
          td
            => link_to "Profile", admin_user_path(user)
            => link_to "Edit", edit_admin_user_path(user)
            -if current_user.id != user.id
              =< link_to "Delete", admin_user_path(user), method: "delete"

.mdl-grid
  .mdl-cell.mdl-cell--10-col
    = paginate @users
  .mdl-cell.mdl-cell--2-col
    = page_entries_info @users

app/views/admin/users/new.html.slim
h4 Create new user
= render partial: 'form', locals: { user: @user, url: admin_users_path }

app/views/admin/users/show.html.slim
h1 User profile
p
  span First Name:&nbsp;
  strong= @user.first_name
p
  span Last Name:&nbsp;
  strong= @user.last_name
p
  span Email:&nbsp;
  strong= @user.email

= link_to "Back", admin_users_path, class: "mdl-button mdl-js-button mdl-button--raised"

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Task Manager"
    link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"
    = stylesheet_link_tag "application", media: "all"
    = csrf_meta_tags
    - if !Rails.env.development?
      = stylesheet_packs_with_chunks_tag "application", media: "all"


  body
    = javascript_packs_with_chunks_tag 'application'
    header.mdl-layout__header
      .mdl-layout__header-row
        .material-icons tab
        label.mdl-button.mdl-js-button.mdl-button--icon
          i.material-icons
        span.mdl-layout-title
          = "Task Manager"
        .mdl-layout-spacer
        nav.mdl-navigation
          = link_to "Board", board_path, class: 'mdl-navigation__link'
          - if current_user
            - if current_user.is_a? Admin
              = link_to "Admin page", admin_users_url, class: 'mdl-navigation__link'
            i.material-icons person
            = current_user.first_name
            = link_to "Log out", session_path, method: "delete", confirm: "confirm?", class: 'mdl-navigation__link'
          - else
            = link_to "Sign in", new_session_path, class: 'mdl-navigation__link'
            = link_to "Sign up", new_developer_path, class: 'mdl-navigation__link'  
    main#main.mdl-layout__content
      .page-content
        = yield
    footer#footer.mdl-mini-footer
      .mdl-mini-footer__left-section
        .mdl-logo
          | &copy; Dualboot Learn 2022

app/views/web/boards/show.html.slim
h1 Web::Boards#show
p Find me in app/views/web/boards/show.html.slim

app/views/web/developers/new.html.slim
h3 Sign up

= simple_form_for @developer do |f|
  p
    = f.input :first_name
    = f.input :last_name
    = f.input :email
    = f.input :password
    = f.input :password_confirmation
  p
    = f.button :submit, "Sign up"